### ISSUE TITLE
development sprint to v0.3.0

### ISSUE THREAD

**Issue by goldingn** [greta-dev/greta#207]
This issue is for planning and tracking progress in a two-week development sprint 13-24 August 2018. The aim is to release a stable release of greta (v0.3) which implements a bunch of new features and substantially increases the usability and extensibility of greta. The work comprises 5 packets, and I'll keep editing this to keep track of the work in those packets:

### 1. Implement new features on dev
 - this will close a lot of open issues and polish of some 80% complete new features currently floating around on gists. These are some priorities:
 - [x] #123 (matrix-parametered multivariate distributions)
 - [x] #105, #203 (initial values)
 - [x] #212 (catch numerical errors)
 - [x] #84 (improved mixture distribution)
 - [x] #70 (ODE solver)
 - [x] #151 (placeholders not constants)
 - [x] #83 (greta arrays extend arrays, not lists)
 - [x] #110 (generalise and add optimisers)
 - [x] #111 (catch discrete ops)
 - [x] #86 (implement computational representations)
 - [x] #209 (simplex variables)
 - [x] #208 (parallel progress bars)
 - [x] #211 (optimise slow DAG-definition code)
### 2. Merge and consolidate all the PRs
 - ~~example models and documentation in #200 & #172~~  
 - ~~an MH sampler in #173 & implement other samplers of interest (e.g. slice sampling)~~
### 3. Host the website in its own repo
 - ~~this will merge PR #167, and close #140 and #162~~
 - ~~hosting at a new URL (with redirection from the current github pages)~~
 - ~~add a discourse forum for non-issue modelling questions (stretch goal)~~
### 4. Release greta v0.3
 - ~~get test coverage high~~
 - ~~add posterior checks to Travis for release candidates~~
 - ~~solidify TF & TF probability dependency versions~~
 - ~~proofread new examples and vignettes~~
 - ~~add new contributors to DESCRIPTION~~
